// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(LogicTenacityDbContext))]
    [Migration("20240415102535_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Server.Models.File", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UploaderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FileId");

                    b.HasIndex("UploaderId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Server.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AvatarId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Github")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Linkedin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordTokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "",
                            Country = "",
                            DateAdded = new DateTime(2024, 4, 15, 12, 25, 34, 281, DateTimeKind.Local).AddTicks(8181),
                            DateOfBirth = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin",
                            FirstName = "Logic",
                            Github = "",
                            IsDisabled = false,
                            LastName = "Tenacity",
                            Linkedin = "",
                            Password = "$2a$10$NuvawBVu0YsvLskgdhvs/e48AlcRe7D6tHVWB70tsZYbCl/00j7Vi",
                            PhoneNumber = "",
                            RoleId = 1,
                            Status = ""
                        },
                        new
                        {
                            Id = 2,
                            City = "",
                            Country = "",
                            DateAdded = new DateTime(2024, 4, 15, 12, 25, 34, 348, DateTimeKind.Local).AddTicks(6741),
                            DateOfBirth = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "pera@gmail.com",
                            FirstName = "Pera",
                            Github = "",
                            IsDisabled = false,
                            LastName = "Peric",
                            Linkedin = "",
                            Password = "$2a$10$j8qa7Pg5xNI79o7d2kkCqexK1pSXw1Pe/nku05rLpJdzOWWS71b/.",
                            PhoneNumber = "",
                            RoleId = 2,
                            Status = ""
                        },
                        new
                        {
                            Id = 3,
                            City = "",
                            Country = "",
                            DateAdded = new DateTime(2024, 4, 15, 12, 25, 34, 414, DateTimeKind.Local).AddTicks(3707),
                            DateOfBirth = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "toma@gmail.com",
                            FirstName = "Toma",
                            Github = "",
                            IsDisabled = false,
                            LastName = "Tomic",
                            Linkedin = "",
                            Password = "$2a$10$hz7ofe5KslwVBSA4yHTtke0va.0099c2XyZgQEbMkZJeFiSMStE4S",
                            PhoneNumber = "",
                            RoleId = 3,
                            Status = ""
                        });
                });

            modelBuilder.Entity("Server.Models.MemberProject", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MemberId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("MemberProjects");
                });

            modelBuilder.Entity("Server.Models.MemberTask", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MemberId", "TaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("MemberTasks");
                });

            modelBuilder.Entity("Server.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = -1,
                            PermissionName = "Edit roles"
                        },
                        new
                        {
                            PermissionId = 1,
                            PermissionName = "Add members"
                        },
                        new
                        {
                            PermissionId = 2,
                            PermissionName = "Deactivate members"
                        },
                        new
                        {
                            PermissionId = 3,
                            PermissionName = "Create project"
                        },
                        new
                        {
                            PermissionId = 4,
                            PermissionName = "Create task"
                        },
                        new
                        {
                            PermissionId = 5,
                            PermissionName = "Delete project"
                        },
                        new
                        {
                            PermissionId = 6,
                            PermissionName = "Delete task"
                        },
                        new
                        {
                            PermissionId = 7,
                            PermissionName = "Add member to task"
                        },
                        new
                        {
                            PermissionId = 8,
                            PermissionName = "Add member to project"
                        },
                        new
                        {
                            PermissionId = 9,
                            PermissionName = "Remove member from task"
                        },
                        new
                        {
                            PermissionId = 10,
                            PermissionName = "Remove member from project"
                        },
                        new
                        {
                            PermissionId = 11,
                            PermissionName = "Change task status"
                        },
                        new
                        {
                            PermissionId = 12,
                            PermissionName = "Change project status"
                        },
                        new
                        {
                            PermissionId = 13,
                            PermissionName = "Change project"
                        },
                        new
                        {
                            PermissionId = 14,
                            PermissionName = "Update task priority"
                        },
                        new
                        {
                            PermissionId = 15,
                            PermissionName = "Add task dependency"
                        },
                        new
                        {
                            PermissionId = 16,
                            PermissionName = "Remove task dependency"
                        },
                        new
                        {
                            PermissionId = 17,
                            PermissionName = "Add task category"
                        },
                        new
                        {
                            PermissionId = 18,
                            PermissionName = "Remove task category"
                        });
                });

            modelBuilder.Entity("Server.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamLeaderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId");

                    b.HasIndex("ProjectStatusId");

                    b.HasIndex("TeamLeaderId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Server.Models.ProjectStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProjectStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "In Preparation"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Closed"
                        },
                        new
                        {
                            Id = 3,
                            Status = "In Progress"
                        });
                });

            modelBuilder.Entity("Server.Models.ProjectTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskPriorityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskStatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TaskCategoryId");

                    b.HasIndex("TaskPriorityId");

                    b.HasIndex("TaskStatusId");

                    b.ToTable("ProjectTasks");
                });

            modelBuilder.Entity("Server.Models.ProjectTaskStatus", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskStatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId", "TaskStatusId");

                    b.HasIndex("TaskStatusId");

                    b.ToTable("ProjectTaskStatuses");
                });

            modelBuilder.Entity("Server.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFallback")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            IsDefault = true,
                            IsFallback = false,
                            RoleName = "Administrator"
                        },
                        new
                        {
                            RoleId = 2,
                            IsDefault = true,
                            IsFallback = false,
                            RoleName = "Project Manager"
                        },
                        new
                        {
                            RoleId = 3,
                            IsDefault = true,
                            IsFallback = true,
                            RoleName = "Worker"
                        });
                });

            modelBuilder.Entity("Server.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = -1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 18
                        });
                });

            modelBuilder.Entity("Server.Models.TaskActivity", b =>
                {
                    b.Property<int>("TaskActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskActivityTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskActivityId");

                    b.HasIndex("MemberId");

                    b.HasIndex("ProjectTaskId");

                    b.HasIndex("TaskActivityTypeId");

                    b.ToTable("TaskActivities");
                });

            modelBuilder.Entity("Server.Models.TaskActivityType", b =>
                {
                    b.Property<int>("TaskActivityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskActivityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskActivityTypeId");

                    b.ToTable("TaskActivityTypes");

                    b.HasData(
                        new
                        {
                            TaskActivityTypeId = 1,
                            TaskActivityName = "Review"
                        },
                        new
                        {
                            TaskActivityTypeId = 2,
                            TaskActivityName = "Update"
                        },
                        new
                        {
                            TaskActivityTypeId = 3,
                            TaskActivityName = "Bug fix"
                        });
                });

            modelBuilder.Entity("Server.Models.TaskCategory", b =>
                {
                    b.Property<int>("TaskCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskCategoryID");

                    b.ToTable("TaskCategories");

                    b.HasData(
                        new
                        {
                            TaskCategoryID = 1,
                            CategoryName = "None"
                        });
                });

            modelBuilder.Entity("Server.Models.TaskComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaskComments");
                });

            modelBuilder.Entity("Server.Models.TaskDependency", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DependentTaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskId", "DependentTaskId");

                    b.HasIndex("DependentTaskId");

                    b.ToTable("TaskDependencies");
                });

            modelBuilder.Entity("Server.Models.TaskPriority", b =>
                {
                    b.Property<int>("TaskPriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskPriorityId");

                    b.ToTable("TaskPriority");

                    b.HasData(
                        new
                        {
                            TaskPriorityId = 1,
                            Name = "Low"
                        },
                        new
                        {
                            TaskPriorityId = 2,
                            Name = "Medium"
                        },
                        new
                        {
                            TaskPriorityId = 3,
                            Name = "High"
                        });
                });

            modelBuilder.Entity("Server.Models.TaskStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaskStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDefault = true,
                            Name = "New"
                        },
                        new
                        {
                            Id = 2,
                            IsDefault = true,
                            Name = "In Progress"
                        },
                        new
                        {
                            Id = 3,
                            IsDefault = true,
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("Server.Models.File", b =>
                {
                    b.HasOne("Server.Models.Member", "Uploader")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Server.Models.Member", b =>
                {
                    b.HasOne("Server.Models.File", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.HasOne("Server.Models.Role", "Role")
                        .WithMany("Members")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avatar");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Server.Models.MemberProject", b =>
                {
                    b.HasOne("Server.Models.Member", "Member")
                        .WithMany("MemberProjects")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Project", "Project")
                        .WithMany("MemberProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Server.Models.MemberTask", b =>
                {
                    b.HasOne("Server.Models.Member", "Member")
                        .WithMany("Tasks")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.ProjectTask", "Task")
                        .WithMany("Members")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Server.Models.Project", b =>
                {
                    b.HasOne("Server.Models.ProjectStatus", "ProjectStatus")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Member", "TeamLeader")
                        .WithMany("ProjectsLead")
                        .HasForeignKey("TeamLeaderId");

                    b.Navigation("ProjectStatus");

                    b.Navigation("TeamLeader");
                });

            modelBuilder.Entity("Server.Models.ProjectTask", b =>
                {
                    b.HasOne("Server.Models.Project", "Project")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.TaskCategory", "TaskCategory")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("TaskCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.TaskPriority", "TaskPriority")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("TaskPriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.TaskStatus", "TaskStatus")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("TaskStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("TaskCategory");

                    b.Navigation("TaskPriority");

                    b.Navigation("TaskStatus");
                });

            modelBuilder.Entity("Server.Models.ProjectTaskStatus", b =>
                {
                    b.HasOne("Server.Models.Project", "Project")
                        .WithMany("ProjectTaskStatuses")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.TaskStatus", "TaskStatus")
                        .WithMany("ProjectTaskStatuses")
                        .HasForeignKey("TaskStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("TaskStatus");
                });

            modelBuilder.Entity("Server.Models.RolePermission", b =>
                {
                    b.HasOne("Server.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Server.Models.TaskActivity", b =>
                {
                    b.HasOne("Server.Models.Member", "Member")
                        .WithMany("TaskActivities")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.ProjectTask", "ProjectTask")
                        .WithMany("TaskActivities")
                        .HasForeignKey("ProjectTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.TaskActivityType", "TaskActivityType")
                        .WithMany("TaskActivities")
                        .HasForeignKey("TaskActivityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("ProjectTask");

                    b.Navigation("TaskActivityType");
                });

            modelBuilder.Entity("Server.Models.TaskDependency", b =>
                {
                    b.HasOne("Server.Models.ProjectTask", "DependentTask")
                        .WithMany("DependentTasks")
                        .HasForeignKey("DependentTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.ProjectTask", "Task")
                        .WithMany("Dependencies")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DependentTask");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Server.Models.Member", b =>
                {
                    b.Navigation("MemberProjects");

                    b.Navigation("ProjectsLead");

                    b.Navigation("TaskActivities");

                    b.Navigation("Tasks");

                    b.Navigation("UploadedFiles");
                });

            modelBuilder.Entity("Server.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Server.Models.Project", b =>
                {
                    b.Navigation("MemberProjects");

                    b.Navigation("ProjectTaskStatuses");

                    b.Navigation("ProjectTasks");
                });

            modelBuilder.Entity("Server.Models.ProjectStatus", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Server.Models.ProjectTask", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("DependentTasks");

                    b.Navigation("Members");

                    b.Navigation("TaskActivities");
                });

            modelBuilder.Entity("Server.Models.Role", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Server.Models.TaskActivityType", b =>
                {
                    b.Navigation("TaskActivities");
                });

            modelBuilder.Entity("Server.Models.TaskCategory", b =>
                {
                    b.Navigation("ProjectTasks");
                });

            modelBuilder.Entity("Server.Models.TaskPriority", b =>
                {
                    b.Navigation("ProjectTasks");
                });

            modelBuilder.Entity("Server.Models.TaskStatus", b =>
                {
                    b.Navigation("ProjectTaskStatuses");

                    b.Navigation("ProjectTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
